### ISSUE TITLE
Sanitize user inputs before saving to disk

### ISSUE THREAD

**Issue by calda** [Agile-Puppers/Clean-Water#7]
If the user input somethings like *Stephens, Cal* into a text field in their profile, it would write `username=cal,fullname=Stephens, Cal,password=pass`. `, Cal` would be lost from the key/value pair. We should use URL-style encoding like `%2C` for `,` and `%3D` for `=`, to make the system more resilient.

**Comment by calda** [comment]
Looks to be resolved by #10

**Comment by hugabor** [comment]
sorry...

**Comment by hugabor** [comment]
fixed by 4adb11682a553fa2e5809dc1743f9d195f892dfc
